name: cirilica
description: Simple dart package for converting latin text to Serbian cyrillic and vice versa
version: 1.0.0

homepage: https://github.com/aleksandar-radivojevic/cirilica

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.9.4
